### PR TITLE
Optimizing learn page 🚧

### PR DESCRIPTION
**Pull request by gargajit**
Improving `learn` page:

- added information about the `champion program`
- reordered the headings to move the developer part at the top

### CODE REVIEW

**Comment by amitu** [comment]
Before the "The resources are distributed in the following categories.", add:

> Join 3000+ developers learning `fastn` on [our Discord server](https://fastn.com/discord/). You can also join [`fastn` WhatsApp channel](https://whatsapp.com/channel/0029Va6XNHZ9WtCCkv3KvC0X) to stay up to date about fastn.

**Comment by amitu** [comment]
In the first line, change "building dynamic apps." to "building full-stack web applications".

**Comment by amitu** [comment]
Maybe the discord / whatsapp stuff we put under a heading "Getting Help and Staying Up To Date".

**Comment by gargajit** [comment]
> Maybe the discord / whatsapp stuff we put under a heading "Getting Help and Staying Up To Date".

This is done

**Pull request merged**
