### PR TITLE
new blog - intimidation of programming

### PR DESCRIPTION
**Pull request by nandhinidevie**
Created my first blog post on fastn.com.

[Rendered version](https://fastncom-git-intimidation-of-programming-fifthtry.vercel.app/blog/intimidation-of-programming/)

### CODE REVIEW

**Comment by amitu** [comment]
@gargajit, please help @nandhinidevie include both the source code and rendered version as proper ftd. 

@nandhinidevie, we consider including image as "smell". In other frameworks including components by others is too much work so people include images, we have much better story so we show off that by including "live" components as much as possible.

You can show that off further by including component with interaction, animation etc. Ask @gsalunke to add some interaction to those message stuff, or work with Yashveer to design some component for such demos. We have used this chat one since a long, I want fresher examples :-)

**Comment by gargajit** [comment]
> @gargajit, please help @nandhinidevie include both the source code and rendered version as proper ftd.
> 
> @nandhinidevie, we consider including image as "smell". In other frameworks including components by others is too much work so people include images, we have much better story so we show off that by including "live" components as much as possible.
> 


Sure @amitu 

Also, We have removed the image and used the `chat-female-avatar` component instead by importing `fastn.com/ftd`

**Comment by amitu** [comment]
@gargajit you saying you have done something but there is only one commit in the PR so far. Is it not pushed yet?

**Comment by gargajit** [comment]
@amitu I have explained Nandhini. We saw it on her local.
Nandhini will push her changes. She just went for lunch.

**Pull request merged**
