### PR TITLE
new blog

### PR DESCRIPTION
**Pull request by nandhinidevie**
[Rendered Version](https://fastncom-git-blog-paradigms-fifthtry.vercel.app/)

### CODE REVIEW

**Comment by amitu** [comment]
@nandhinidevie delete _Users_E.KRITHIKA_OneDrive_Desktop_fastn.com/fastn folder.

**Comment by amitu** [comment]
@Arpita-Jaiswal do you know the cause of these folders? Can we put `*fastn.com_*` in our `.gitignore` to make this go away?

**Comment by Arpita-Jaiswal** [comment]
@Heulitig @harshdoesdev Is this not fixed yet? https://github.com/fastn-stack/fastn.com/pull/488#issuecomment-1778956448

**Comment by harshdoesdev** [comment]
> @Heulitig @harshdoesdev Is this not fixed yet? [#488 (comment)](https://github.com/fastn-stack/fastn.com/pull/488#issuecomment-1778956448)

No, it has not been fixed yet. Since it is occurring on Windows systems only, and I only have Mac/Linux systems, I was not able to work on this. I will try to create a virtual machine and investigate it.

**Comment by amitu** [comment]
@harshdoesdev add a .gitignore entry in this repo for now so we do not have to waste time while it is getting fixed.

**Comment by nandhinidevie** [comment]
> @nandhinidevie the title is wrong: Benefits of being a strongly typed language. This post covers more than types. Let me take a make some changes to this post.

**Pull request merged**
